"use client";

import { useMemo, useState } from "react";
import { pipelineMetrics, sumActivities } from "@/lib/metrics";

// Supabase's generated database types replace this boundary after schema promotion.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
type Data = { contacts: Row[]; activities: Row[]; opportunities: Row[]; accounts: Row[]; error: string | null; updatedAt: string };
const tabs = ["Visão diária", "Dia anterior", "Prospecção", "Reunião executiva", "Pipeline", "Contas prioritárias"] as const;
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo" }).format(new Date(`${value}T12:00:00-03:00`)) : "—";

export function Cockpit({ initialData }: { initialData: Data }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>(tabs[0]);
  const [query, setQuery] = useState("");
  const filteredContacts = useMemo(() => initialData.contacts.filter((row) => `${row.name} ${row.account?.canonical_name ?? ""} ${row.status_raw ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))), [initialData.contacts, query]);
  const activityTotals = sumActivities(initialData.activities.map((row) => ({ contacts: row.contacts_count, invites: row.invites_count, messages: row.messages_count, replies: row.replies_count, conversations: row.conversations_count, meetings: row.meetings_count, opportunities: row.opportunities_count })));
  const pipeline = pipelineMetrics(initialData.opportunities.map((row) => ({ value_amount: row.value_amount, probability: row.probability, stage: row.stage })));
  return <div className="shell"><aside><div className="brand">ANTLIA<small>COCKPIT COMERCIAL</small></div><nav aria-label="Visões do cockpit">{tabs.map((name) => <button key={name} className={tab === name ? "active" : ""} onClick={() => setTab(name)}>{name}</button>)}</nav></aside><main><header><div><h1>{tab}</h1><p>Fatos, próximos passos e decisões — sem inflar o pipeline.</p></div><span className="updated">Atualizado {new Date(initialData.updatedAt).toLocaleString("pt-BR")}</span></header><section className="content">{initialData.error && <div className="alert" role="alert">Não foi possível carregar a base: {initialData.error}</div>}<div className="filters"><input aria-label="Buscar conta ou contato" placeholder="Buscar conta ou contato" value={query} onChange={(e) => setQuery(e.target.value)}/></div>
  {tab === "Visão diária" && <><div className="kpis"><Kpi label="Pipeline aberto" value={money.format(pipeline.total)}/><Kpi label="Pipeline ponderado" value={money.format(pipeline.weighted)}/><Kpi label="Contatos na base" value={String(initialData.contacts.length)}/><Kpi label="Conversas relevantes" value={String(activityTotals.conversations)}/><Kpi label="Reuniões" value={String(activityTotals.meetings)}/></div><Panel title="Prioridades de hoje"><Empty text="As próximas ações serão exibidas após a promoção reconciliada da migração."/></Panel></>}
  {tab === "Dia anterior" && <Panel title="Atividades registradas"><ActivityTable rows={initialData.activities}/></Panel>}
  {tab === "Prospecção" && <><div className="kpis"><Kpi label="Contatos trabalhados" value={String(activityTotals.contacts)}/><Kpi label="Convites" value={String(activityTotals.invites)}/><Kpi label="Mensagens" value={String(activityTotals.messages)}/><Kpi label="Respostas" value={String(activityTotals.replies)}/><Kpi label="Conversas" value={String(activityTotals.conversations)}/></div><Panel title={`Lista de prospecção · ${filteredContacts.length}`}><ContactTable rows={filteredContacts}/></Panel></>}
  {tab === "Reunião executiva" && <><div className="hero"><div><small>RESUMO EXECUTIVO</small><h2>{pipeline.count ? `${pipeline.count} oportunidades abertas` : "Nenhuma oportunidade qualificada registrada."}</h2><p>Indicadores derivados exclusivamente de dados persistidos no Supabase.</p></div></div><Panel title="Atividade consolidada"><ActivityTable rows={initialData.activities}/></Panel></>}
  {tab === "Pipeline" && <Panel title={`Pipeline · ${initialData.opportunities.length}`}><OpportunityTable rows={initialData.opportunities}/></Panel>}
  {tab === "Contas prioritárias" && <div className="accountGrid">{initialData.accounts.slice(0, 30).map((row) => <article className="card" key={row.id}><small>CONTA</small><h3>{row.canonical_name}</h3><p>{initialData.contacts.filter((c) => c.account?.id === row.id).length} contatos mapeados</p></article>)}</div>}
  </section></main></div>;
}

function Kpi({ label, value }: { label: string; value: string }) { return <article className="card kpi"><small>{label}</small><strong>{value}</strong></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="card panel"><h2>{title}</h2><div className="tableWrap">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function ContactTable({ rows }: { rows: Row[] }) { return rows.length ? <table><thead><tr><th>Contato / empresa</th><th>Cargo</th><th>Responsável</th><th>Status</th><th>Último contato</th><th>LinkedIn</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><b>{r.name}</b><small>{r.account?.canonical_name}</small></td><td>{r.role_title || "—"}</td><td>{r.owner_name || "—"}</td><td><span className="pill">{r.status_raw || "A validar"}</span></td><td>{date(r.last_contact_at?.slice(0,10))}</td><td>{r.linkedin_url ? <a href={r.linkedin_url} target="_blank" rel="noreferrer">Abrir perfil</a> : "—"}</td></tr>)}</tbody></table> : <Empty text="Nenhum contato encontrado."/>; }
function ActivityTable({ rows }: { rows: Row[] }) { return rows.length ? <table><thead><tr><th>Data</th><th>Responsável</th><th>Canal</th><th>Contatos</th><th>Convites</th><th>Mensagens</th><th>Respostas</th><th>Conversas</th><th>Reuniões</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{date(r.effective_on)}</td><td>{r.owner_name || "—"}</td><td>{r.channel?.name || "—"}</td><td>{r.contacts_count}</td><td>{r.invites_count}</td><td>{r.messages_count}</td><td>{r.replies_count}</td><td>{r.conversations_count}</td><td>{r.meetings_count}</td></tr>)}</tbody></table> : <Empty text="Nenhuma atividade registrada."/>; }
function OpportunityTable({ rows }: { rows: Row[] }) { return rows.length ? <table><thead><tr><th>Conta / oportunidade</th><th>Responsável</th><th>Estágio</th><th>Valor</th><th>Prob.</th><th>Fechamento</th><th>Próxima ação</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><b>{r.account?.canonical_name}</b><small>{r.title}</small></td><td>{r.owner_name || "—"}</td><td><span className="pill">{r.stage?.name || "A validar"}</span></td><td>{money.format(Number(r.value_amount))}</td><td>{r.probability}%</td><td>{date(r.expected_close_on)}</td><td>{r.next_action}</td></tr>)}</tbody></table> : <Empty text="Nenhuma oportunidade registrada."/>; }
